name: Local Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build image
        run: docker build -t localapp:ci ./backend
      - name: Run container and test
        run: |
          docker run -d -p 5000:5000 --name app localapp:ci
          echo "Waiting for app to be healthy..."
          for i in {1..10}; do
            if curl -fs http://localhost:5000/health; then
              echo "Health check passed!"
              break
            else
              echo "Not ready yet ($i)"
              sleep 2
            fi
          done
          docker logs app
      - name: Cleanup container
        if: always()
        run: docker rm -f app || true
